version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: patient_service_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: hospital_management
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - patient_network

  patient-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: patient_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/hospital_management?authSource=admin
    depends_on:
      - mongodb
    networks:
      - patient_network

volumes:
  mongodb_data:

networks:
  patient_network:
    driver: bridge
